'use server';

import admin from './firebase-admin';

const db = admin.firestore();

/**
 * The structure of a single entry in the activity log.
 */
export type ActivityLog = {
  id?: string; // Optional: The ID will be generated by Firestore
  timestamp: admin.firestore.FieldValue; // Use the server timestamp for accuracy
  userId: string; // The ID of the user who performed the action
  action: string; // The type of action (e.g., 'PLOT_SAVED', 'REPORT_APPROVED')
  details: Record<string, any>; // A flexible object for action-specific data
};

/**
 * Writes an entry to the activity log.
 * 
 * @param logEntry The data for the log entry.
 */
export async function logActivity(logEntry: Omit<ActivityLog, 'id' | 'timestamp'>): Promise<void> {
  try {
    const activityCollection = db.collection('activity');
    await activityCollection.add({
      ...logEntry,
      timestamp: admin.firestore.FieldValue.serverTimestamp(), // Use the server timestamp
    });
  } catch (error) {
    console.error("Error writing to activity log:", error);
    // We will not throw an error here, as logging should not block the main action.
    // In a real-world scenario, you might want to send this to a monitoring service.
  }
}
